import React from 'react';
import ReactMarkdown from 'react-markdown';
import { FileDown, CheckCircle, AlertTriangle, FileText } from 'lucide-react';

interface Step5Props {
  report: string;
}

const Step5Analyst: React.FC<Step5Props> = ({ report }) => {
  
  const handleDownload = () => {
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Model_Validation_Report.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!report) {
      return (
        <div className="flex flex-col items-center justify-center h-64 text-slate-400 bg-slate-50/50 rounded-xl border border-dashed border-slate-300">
            <AlertTriangle className="w-8 h-8 mb-2 opacity-50" />
            <p>No analysis report generated yet.</p>
        </div>
      );
  }

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500 pb-20">
      
      {/* Header Actions */}
      <div className="flex justify-between items-center bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
          <div>
              <h2 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                  <CheckCircle className="h-5 w-5 text-emerald-500" />
                  Validation & Critical Analysis
              </h2>
              <p className="text-xs text-slate-500">Generated by Gemini 2.5 Pro Analyst Agent</p>
          </div>
          <button 
            onClick={handleDownload}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-lg transition-colors shadow-sm"
          >
            <FileDown className="h-4 w-4" /> Download Report
          </button>
      </div>

      {/* Report Content */}
      <article className="prose prose-slate prose-sm max-w-none bg-white p-8 rounded-xl shadow-sm border border-slate-200">
        <div className="markdown-prose">
            <ReactMarkdown
                components={{
                    h1: ({node, ...props}) => <h1 className="text-2xl font-bold text-slate-900 border-b pb-2 mb-4 mt-6 first:mt-0" {...props} />,
                    h2: ({node, ...props}) => <h2 className="text-xl font-semibold text-slate-800 mt-6 mb-3 flex items-center gap-2" {...props} />,
                    h3: ({node, ...props}) => <h3 className="text-lg font-medium text-slate-700 mt-4 mb-2" {...props} />,
                    ul: ({node, ...props}) => <ul className="list-disc list-outside ml-6 space-y-1 text-slate-600" {...props} />,
                    ol: ({node, ...props}) => <ol className="list-decimal list-outside ml-6 space-y-1 text-slate-600" {...props} />,
                    li: ({node, ...props}) => <li className="pl-1" {...props} />,
                    p: ({node, ...props}) => <p className="leading-relaxed text-slate-600 mb-4" {...props} />,
                    code: ({node, ...props}) => <code className="bg-slate-100 text-pink-600 px-1.5 py-0.5 rounded text-xs font-mono" {...props} />,
                    pre: ({node, ...props}) => <pre className="bg-slate-900 text-slate-300 p-4 rounded-lg overflow-x-auto text-xs my-4" {...props} />,
                    blockquote: ({node, ...props}) => <blockquote className="border-l-4 border-indigo-500 pl-4 italic text-slate-500 my-4 bg-slate-50 py-2 pr-2 rounded-r" {...props} />,
                }}
            >
                {report}
            </ReactMarkdown>
        </div>
      </article>

    </div>
  );
};

export default Step5Analyst;